# Generated by Django 5.0.4 on 2026-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bottle_price",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "plant_name",
                    models.CharField(
                        default="Fiver Star Water Filter Plant", max_length=200
                    ),
                ),
                ("plant_address", models.TextField(blank=True)),
                ("plant_phone", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plant Settings",
                "verbose_name_plural": "Plant Settings",
                "db_table": "plant_settings",
            },
        ),
    ]
